#!/bin/sh

#logger ACTION=$ACTION DEVPATH=$DEVPATH SUBSYSTEM=$SUBSYSTEM DEVTYPE=$DEVTYPE PRODUCT=$PRODUCT MODALIAS=$MODALIAS

PLATFORM='sun8iw7p1|sun50iw2p1'
if ! grep -E $PLATFORM /sys/class/sunxi_info/sys_info -q; then
    logger "only support $PLATFORM. exiting..."
    exit 0
fi

DIR=/root/.friendlyelec/
if [ "${DEVTYPE}" = usb_device -a "${PRODUCT}" = "bda/c811/200" ]; then
    MODULE=8821cu
    TARGET=wlan${MODULE}

    WIFI_PATH=`echo ${DEVPATH} | cut -d/ -f 3-`
    RADIO=`uci show wireless | grep ${WIFI_PATH} | cut -d. -f 2`
    #logger "${MODULE}: ${WIFI_PATH} ${RADIO}"

    if [ "${ACTION}" = bind ]; then
        logger -t ${MODULE} "insert"

        # Rename physical dev
        # Unimplement(cause error), please FIX ME
        FULL_PATH=`find /sys/${DEVPATH} -name wlan*`
        ADDRESS=`cat ${FULL_PATH}/address`
        WLAN=`basename ${FULL_PATH}`
        # logger -t ${MODULE} "rename ${WLAN} to $TARGET"
        # ip link set ${WLAN} name $TARGET

        mkdir -p ${DIR}
        if [ -e ${DIR}/first_insert_${MODULE} ]; then
            logger -t ${MODULE} "not first init"
        else
            touch ${DIR}/first_insert_${MODULE}
            logger -t ${MODULE} "first init"

            # Enable wifi and change ssid
            uci set wireless.${RADIO}.disabled=0
            uci set wireless.default_${RADIO}.ssid=OpenWrt-${MODULE}-${ADDRESS}
            uci set wireless.default_${RADIO}.encryption=psk2
            uci set wireless.default_${RADIO}.key=password
            uci commit 
        fi
        
        wifi reload
        sleep 1
        /etc/init.d/network restart
    elif [ "${ACTION}" = unbind ]; then
        logger -t ${MODULE} "eject"

        # User may change ${RADIO}'s config. So we don't modify it when eject.
        #uci delete wireless.${RADIO}
        #uci delete wireless.default_${RADIO}
        #uci commit
        #wifi reload
    fi
fi
